#version 450
layout(local_size_x = 64) in;
layout(set = 0, binding = 0, std430) buffer Statistics { uvec4 stats[]; };
layout(set = 0, binding = 1, std430) writeonly buffer Report { uint report[]; };
layout(push_constant) uniform Parameters { uint word_offset; uint reset; } parameters;
void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= 256) return;
    if (i < 16) report[parameters.word_offset + i] = i == 0 ? 1 : 0;
    uvec4 value = stats[i];
    report[parameters.word_offset + 16 + i * 2] = value.y;
    report[parameters.word_offset + 17 + i * 2] = ((value.x & 15u) << 24u) | min(value.y, 0xffffffu);
    if (parameters.reset != 0) stats[i] = uvec4(15, 0, 0, 0);
}
